
USE OCTOBER_CLASS_2024;

SELECT *
FROM SALES_TABLE;

-- DATA CLEANING : CHANGE DATATYPES OF COLUMNS | DELECT UNWANTED COLUMNS

ALTER TABLE SALES_TABLE
DROP COLUMN ORDER_PRIORITY, SALES_CHANNEL;









-- KPI 1 - COMPUTE TOTAL PROFIT FOR ALL REGIONS #
-- THE DATA WAS GENERATED FROM DIFFERENT SOURCES AND THERE IS A NEED TO WORK WITH 3 DATA TABLES

SELECT DISTINCT REGION,
SUM(TOTAL_PROFIT) AS 'TOTAL PROFIT'
FROM
CUSTOMER_TABLE
JOIN
PURCHASE_TABLE
ON
CUSTOMER_TABLE.ORDER_ID = PURCHASE_TABLE.ORDER_ID
GROUP BY REGION;







-- KPI 2 - CALCULATE THE TOTAL REVENUE MADE ANNUALLY #

SELECT *
FROM CUSTOMER_TABLE,
ORDER_TABLE,
PURCHASE_TABLE;

SELECT DISTINCT YEAR (ORDER_DATE) AS 'YEAR',
SUM(TOTAL_REVENUE) AS 'TOTAL REVENUE'
FROM
ORDER_TABLE
INNER JOIN
PURCHASE_TABLE
ON
ORDER_TABLE.ORDER_ID = PURCHASE_TABLE.ORDER_ID
GROUP BY YEAR (ORDER_DATE);









-- KPI 3 - COMPARE TOTAL QUANTITY SOLD YEAR BY YEAR FOR EACH ITEM TYPE #

SELECT *
FROM CUSTOMER_TABLE,
ORDER_TABLE,
PURCHASE_TABLE;


SELECT ITEM_TYPE,
YEAR(ORDER_DATE) AS 'YEAR',
SUM(UNITS_SOLD) AS 'TOTAL QTY SOLD'

FROM ORDER_TABLE
JOIN
PURCHASE_TABLE

ON
ORDER_TABLE.ORDER_ID = PURCHASE_TABLE.ORDER_ID

GROUP BY YEAR(ORDER_DATE),ITEM_TYPE;

-- KPI 3 - COMPARE TOTAL QUANTITY SOLD YEAR BY YEAR FOR EACH ITEM TYPE USING 1 DATA TABLE#

SELECT DISTINCT ITEM_TYPE,
YEAR(ORDER_DATE) AS 'YEAR',
SUM(UNITS_SOLD) AS 'TOTAL UNITS SOLD'
FROM
SALES_TABLE
GROUP BY
YEAR(ORDER_DATE),ITEM_TYPE;










-- KPI 4 - RATE OF REVENUE ACHIEVED IN ALL REGIONS
SELECT *
FROM CUSTOMER_TABLE,
ORDER_TABLE,
PURCHASE_TABLE;

-- CALCULATE THE GRAND TOTAL REVENUE FOR ALL REGIONS
SELECT
	SUM(TOTAL_REVENUE) AS 'GRAND TOTAL REVENUE'
FROM
	PURCHASE_TABLE;

-- CALCULATE THE TOTAL REVENUE FOR EACH REGION

SELECT REGION,
	SUM(TOTAL_REVENUE) AS 'TOTAL REVENUE'
FROM
	CUSTOMER_TABLE
JOIN
	PURCHASE_TABLE
ON
	CUSTOMER_TABLE.ORDER_ID = PURCHASE_TABLE.ORDER_ID
GROUP BY
	REGION;

-- THE RATE OF REVENUE FOR EACH REGION

SELECT REGION,
	SUM(TOTAL_REVENUE) AS 'TOTAL REVENUE',
	SUM(TOTAL_REVENUE)*100/(SELECT SUM(TOTAL_REVENUE)FROM PURCHASE_TABLE) AS 'RATE OF REVENUE'

FROM
	CUSTOMER_TABLE
JOIN
	PURCHASE_TABLE
ON
	CUSTOMER_TABLE.ORDER_ID = PURCHASE_TABLE.ORDER_ID

GROUP BY
	REGION;









-- KPI 5 - DETERMINE THE GROSS PROFIT MARGIN FOR EACH ITEM SOLD
SELECT *
FROM CUSTOMER_TABLE,
ORDER_TABLE,
PURCHASE_TABLE;

SELECT
	DISTINCT ITEM_TYPE,
	AVG((TOTAL_REVENUE - TOTAL_COST)/TOTAL_REVENUE)*100 AS 'PROFIT MARGIN'
FROM
	ORDER_TABLE
JOIN
	PURCHASE_TABLE
ON
	ORDER_TABLE.ORDER_ID = PURCHASE_TABLE.ORDER_ID
GROUP BY
ITEM_TYPE;









